from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

CRYPTO_LEXICON_EN: dict[str, float] = {
    # ── Strongly bullish ──
    "moon": 3.2,
    "mooning": 3.4,
    "moonshot": 3.3,
    "lambo": 3.0,
    "bullish": 2.8,
    "bull": 2.0,
    "pump": 2.5,
    "pumping": 2.7,
    "breakout": 2.5,
    "rally": 2.4,
    "surge": 2.6,
    "soaring": 2.8,
    "skyrocket": 3.0,
    "ath": 2.5,
    "hodl": 1.8,
    "diamond hands": 2.5,
    "diamondhands": 2.5,
    "wagmi": 2.5,
    "gm": 1.0,
    "lfg": 2.5,
    "alpha": 2.0,
    "gem": 2.2,
    "100x": 3.0,
    "10x": 2.5,
    "1000x": 3.2,
    "undervalued": 2.0,
    "accumulate": 1.8,
    "accumulating": 1.8,
    "btfd": 2.2,
    "buy the dip": 2.0,
    "send it": 2.0,
    "parabolic": 2.8,
    "supercycle": 2.5,
    "flippening": 2.0,
    "adoption": 1.8,
    "institutional": 1.5,
    "whale": 1.2,
    "whales": 1.2,
    "airdrop": 1.5,
    "staking": 1.2,
    "yield": 1.0,
    "defi": 1.0,
    "bullrun": 3.0,
    "bull run": 3.0,
    "green candle": 2.0,
    "green candles": 2.2,
    "massive green": 2.5,
    # ── Mildly bullish ──
    "dip": 0.8,
    "buying": 1.0,
    "long": 1.2,
    "longing": 1.3,
    "support": 1.0,
    "bounce": 1.2,
    "recovery": 1.5,
    "reversal": 1.0,
    "oversold": 1.2,
    # ── Strongly bearish ──
    "rug": -3.0,
    "rugged": -3.2,
    "rugpull": -3.2,
    "rug pull": -3.2,
    "scam": -3.0,
    "scammer": -3.0,
    "ponzi": -3.0,
    "hack": -2.8,
    "hacked": -3.0,
    "exploit": -2.8,
    "exploited": -3.0,
    "dump": -2.5,
    "dumping": -2.7,
    "crash": -2.8,
    "crashed": -3.0,
    "crashing": -2.9,
    "rekt": -3.0,
    "liquidated": -2.8,
    "liquidation": -2.8,
    "capitulation": -2.5,
    "bear": -2.0,
    "bearish": -2.8,
    "ngmi": -2.5,
    "dead": -2.5,
    "dead cat bounce": -2.0,
    "bloodbath": -3.0,
    "nuke": -2.8,
    "nuked": -3.0,
    "plunge": -2.8,
    "plunging": -2.9,
    "tank": -2.5,
    "tanking": -2.7,
    "collapse": -3.0,
    "collapsed": -3.2,
    "insolvent": -3.0,
    "insolvency": -3.0,
    "bankrupt": -3.2,
    "bankruptcy": -3.2,
    "fraud": -3.0,
    "sec": -1.5,
    "lawsuit": -2.0,
    "fud": -1.8,
    "paper hands": -2.0,
    "paperhands": -2.0,
    "sell off": -2.2,
    "selloff": -2.2,
    "red candle": -2.0,
    "red candles": -2.2,
    "massive red": -2.5,
    "bag holder": -2.0,
    "bagholder": -2.0,
    "exit scam": -3.2,
    "ponzinomics": -3.0,
    # ── Mildly bearish ──
    "short": -1.2,
    "shorting": -1.3,
    "resistance": -0.8,
    "overbought": -1.2,
    "correction": -1.0,
    "pullback": -0.8,
    "fear": -1.5,
    "uncertainty": -1.2,
    "volatile": -0.8,
    "volatility": -0.5,
    # ── Neutral / contextual ──
    "halving": 1.0,
    "etf": 1.2,
    "spot etf": 1.5,
    "regulation": -0.5,
    "ban": -2.0,
    "banned": -2.2,
    "delisting": -2.5,
    "delisted": -2.5,
    "listing": 1.8,
    "listed": 1.5,
}

CRYPTO_LEXICON_ZH: dict[str, float] = {
    # ── 强烈看涨 ──
    "看涨": 2.5,
    "大涨": 2.8,
    "暴涨": 3.2,
    "飙升": 3.0,
    "起飞": 3.0,
    "拉盘": 2.5,
    "拉升": 2.5,
    "冲高": 2.2,
    "新高": 2.5,
    "历史新高": 2.8,
    "突破": 2.0,
    "利好": 2.5,
    "大利好": 3.0,
    "牛市": 2.8,
    "牛回来了": 3.0,
    "抄底": 2.0,
    "加仓": 1.8,
    "建仓": 1.5,
    "满仓": 2.0,
    "梭哈": 2.2,
    "上车": 1.8,
    "财富密码": 2.5,
    "百倍币": 3.0,
    "千倍币": 3.2,
    "万倍币": 3.4,
    "翻倍": 2.5,
    "暴富": 3.0,
    "赚麻了": 3.0,
    "血赚": 2.8,
    "稳了": 2.0,
    "王者归来": 2.5,
    "绝地反击": 2.5,
    "触底反弹": 2.0,
    "强势": 2.0,
    "放量上涨": 2.5,
    "主升浪": 2.8,
    "钻石手": 2.5,
    # ── 温和看涨 ──
    "回调买入": 1.5,
    "逢低买入": 1.5,
    "企稳": 1.2,
    "反弹": 1.5,
    "回暖": 1.5,
    "复苏": 1.5,
    "止跌": 1.0,
    "筑底": 1.0,
    "蓄力": 1.2,
    # ── 强烈看跌 ──
    "暴跌": -3.0,
    "崩盘": -3.2,
    "跳水": -2.8,
    "闪崩": -3.0,
    "腰斩": -3.0,
    "归零": -3.5,
    "清零": -3.5,
    "割韭菜": -3.0,
    "韭菜": -2.0,
    "被割": -2.8,
    "爆仓": -3.0,
    "强平": -2.8,
    "清算": -2.8,
    "血亏": -3.0,
    "亏麻了": -3.0,
    "亏惨了": -2.8,
    "套牢": -2.5,
    "深套": -2.8,
    "站岗": -2.5,
    "高位接盘": -2.5,
    "接盘侠": -2.5,
    "跑路": -3.2,
    "骗局": -3.0,
    "诈骗": -3.2,
    "庞氏": -3.0,
    "资金盘": -3.0,
    "传销": -3.0,
    "黑客": -2.8,
    "被盗": -3.0,
    "漏洞": -2.5,
    "砸盘": -2.8,
    "出货": -2.0,
    "利空": -2.5,
    "大利空": -3.0,
    "熊市": -2.8,
    "寒冬": -2.5,
    "凉了": -2.5,
    "凉凉": -2.8,
    "完蛋": -3.0,
    "药丸": -2.8,
    "垃圾币": -2.8,
    "空气币": -3.0,
    "土狗": -2.0,
    "貔貅盘": -3.0,
    "插针": -2.5,
    "瀑布": -2.8,
    # ── 温和看跌 ──
    "看跌": -2.0,
    "下跌": -1.8,
    "回调": -1.0,
    "回落": -1.2,
    "缩量": -0.8,
    "阴跌": -1.8,
    "横盘": -0.3,
    "震荡": -0.5,
    "恐慌": -2.0,
    "不确定": -1.0,
    "监管": -0.8,
    "禁止": -2.2,
    "下架": -2.5,
    # ── 中性偏正 ──
    "减半": 1.0,
    "上所": 1.8,
    "上币": 1.5,
    "空投": 1.5,
    "质押": 1.0,
    "挖矿": 0.8,
}

EMOJI_LEXICON: dict[str, float] = {
    "🚀": 2.5,
    "🌙": 2.0,
    "🌕": 2.0,
    "💎": 2.2,
    "🙌": 1.5,
    "💪": 1.5,
    "🔥": 1.8,
    "📈": 2.0,
    "💰": 1.5,
    "🤑": 2.0,
    "💵": 1.2,
    "🎉": 1.5,
    "✅": 1.2,
    "👍": 1.0,
    "❤️": 1.0,
    "😍": 1.5,
    "🐂": 2.0,
    "🏆": 1.5,
    "⬆️": 1.5,
    "🟢": 1.5,
    "📉": -2.0,
    "💀": -2.5,
    "☠️": -2.5,
    "🐻": -2.0,
    "😱": -2.0,
    "😭": -1.8,
    "🤮": -2.0,
    "💩": -1.8,
    "🗑️": -2.0,
    "⚠️": -1.2,
    "🚨": -1.5,
    "❌": -1.5,
    "👎": -1.0,
    "⬇️": -1.5,
    "🔴": -1.5,
    "😡": -2.0,
    "🤡": -1.8,
    "🪦": -2.5,
    "📊": 0.0,
    "🤔": -0.3,
    "👀": 0.5,
}

CRYPTO_LEXICON: dict[str, float] = {
    **CRYPTO_LEXICON_EN,
    **CRYPTO_LEXICON_ZH,
    **EMOJI_LEXICON,
}


def create_crypto_vader() -> SentimentIntensityAnalyzer:
    try:
        from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
    except ImportError as exc:
        raise ImportError(
            "vaderSentiment is required: pip install vaderSentiment"
        ) from exc

    analyzer = SentimentIntensityAnalyzer()
    analyzer.lexicon.update(CRYPTO_LEXICON)
    return analyzer
